### ISSUE TITLE
Only Downloaded Thumbnails

### ISSUE THREAD

**Issue by torridgristle** [LudoW809/DevPull#1]
I didn't sign in, had it download 100 pages of search results, and they're all thumbnails. They were also saved as .png despite being JPEGs but that's not as important as the lack of resolution.

**Comment by LudoW809** [comment]
I Will investigate the problem.. Might be a signin or a web scrape recersion issue..
Give me 1-2 days and the problem should be fixed

**Comment by LudoW809** [comment]
**### Solution:**
Error found in url formatting:

https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/ae87168b-d6c4-44ee-8ddc-39f84a8e771e/de32eym-4cf39b97-7a1f-4288-91ae-f1a40ba7f24f.png/v1/fill/**w_622,h_350,q_70,strp**/blood_angels_by_baklaher_de32eym-350t.jpg?token=""

In bold shown is the url which the program recieves..
Give me 1-2 days to implement the option to change resolution/Quality when scraping images
It will be released in the next update (1-2 days)

**Comment by LudoW809** [comment]
Updates Might be delayed 2-3 more days.. sorry for the inconvenience

**Comment by LudoW809** [comment]
Small update added option for file format.. & improved image output quality slightly.
larger and better quality updates will come soon!
